"""Create initial tables

Revision ID: 2237f44529f4
Revises: 
Create Date: 2025-11-07 09:14:46.474712

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2237f44529f4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuarios',
    sa.Column('id_usuario', sa.UUID(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('data_cadastro', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id_usuario'),
    sa.UniqueConstraint('email')
    )
    op.create_table('conversas',
    sa.Column('id_conversa', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('id_usuario', sa.UUID(), nullable=False),
    sa.Column('titulo', sa.String(length=255), nullable=True),
    sa.Column('data_inicio', sa.DateTime(), nullable=True),
    sa.Column('data_ultima_msg', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_conversa')
    )
    op.create_table('documentos',
    sa.Column('id_documento', sa.UUID(), nullable=False),
    sa.Column('id_usuario', sa.UUID(), nullable=False),
    sa.Column('nome_arquivo', sa.String(length=255), nullable=True),
    sa.Column('tipo_documento', sa.String(length=100), nullable=True),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_documento')
    )
    op.create_table('historico_mensagem',
    sa.Column('id_historico', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('id_conversa', sa.BigInteger(), nullable=False),
    sa.Column('id_usuario', sa.UUID(), nullable=False),
    sa.Column('id_documento', sa.UUID(), nullable=True),
    sa.Column('mensagem_texto', sa.Text(), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=True),
    sa.Column('origem_contexto', sa.String(length=50), nullable=True),
    sa.Column('data_hora', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_conversa'], ['conversas.id_conversa'], ),
    sa.ForeignKeyConstraint(['id_documento'], ['documentos.id_documento'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_historico')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('historico_mensagem')
    op.drop_table('documentos')
    op.drop_table('conversas')
    op.drop_table('usuarios')
    # ### end Alembic commands ###
