"""add_password_hash_to_usuarios

Revision ID: b7f45cc86435
Revises: cc777d3f77f2
Create Date: 2025-11-25 12:39:17.614985

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b7f45cc86435'
down_revision: Union[str, Sequence[str], None] = 'cc777d3f77f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('password_hash', sa.String(length=255), nullable=True))
    op.add_column('usuarios', sa.Column('auth_provider', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuarios', 'auth_provider')
    op.drop_column('usuarios', 'password_hash')
    # ### end Alembic commands ###
