"""add auth0_sub to usuarios

Revision ID: cc777d3f77f2
Revises: 2237f44529f4
Create Date: 2025-11-10 16:20:17.986698

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc777d3f77f2'
down_revision: Union[str, Sequence[str], None] = '2237f44529f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('auth0_sub', sa.String(length=255), nullable=True))
    op.create_unique_constraint(None, 'usuarios', ['auth0_sub'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'usuarios', type_='unique')
    op.drop_column('usuarios', 'auth0_sub')
    # ### end Alembic commands ###
